int place_cursor();
int get_next_move_x();
int move_forward(int n);
int move_backward(int n);
int position_cursor();
int reset_x();
int move_first_col();
int move_last_col();
int force_forward(int n);
int move_forward_one();
int move_forward_hs();
int move_backward1(int n);
int move_backward_one();
int move_backward_hs();
int nexttab();
int nexttab3(int x, int o);
int nexttab1();
int get_bow();
int get_eow();
int get_long_eow();
int move_bow();
int move_eow();
int move_word_back();
int move_long_word_back();
